# Generated by Django 3.2 on 2021-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Upload/media/'),
        ),
    ]
