# Generated by Django 3.2 on 2021-04-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
